### ISSUE TITLE
SQL jobs occasionally failed with 401

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/gomaxcompute#27]
**Error message**
```
response error: 401, Unauthorized. The request authorization header is invalid or missing.
```

**Reproduce**

Run `TestQuery` many times.

**Cause**

The sign function in official ODPS Java SDK hashes the URL query parameters in alphabet order. [ref](https://github.com/aliyun/aliyun-odps-java-sdk/blob/7ebc28c0246bc0970a2a24f49214fc9dce68142e/odps-sdk/odps-sdk-core/src/main/java/com/aliyun/odps/account/SecurityUtils.java#L123)

However, our implementation hashes simply by iterating over the parameter maps. However, Iterating over a map has no order guarantee.

**Comment by weiguoz** [comment]
Also, this PR fixed #20
