### ISSUE TITLE
Add support settings for SQL

### ISSUE THREAD

**Issue by koolay** [sql-machine-learning/gomaxcompute#45]
参考[python sdk](https://github.com/aliyun/aliyun-odps-python-sdk/blob/39dd4db5bbd9fca2e884e7e3768b521435ff0225/odps/core.py#L724)

**Comment by koolay** [comment]
没有人维护了吗?

**Comment by weiguoz** [comment]
I apologize for the slow reply.
Would you please give some more explanation for the reason supporting settings.

**Comment by koolay** [comment]
支持配置odps请求参数，例如: odps.sql.timezone, odps.sql.script

**Comment by koolay** [comment]
参考 [python sdk](https://github.com/aliyun/aliyun-odps-python-sdk/blob/39dd4db5bbd9fca2e884e7e3768b521435ff0225/odps/models/tasks.py#L185)

**Comment by Yancey0623** [comment]
hi @koolay , thanks for your suggestion, it's a useful feature for gomaxcompute , I will add this interface in a few days.

**Comment by koolay** [comment]
啥时候可以完成呢，如果没有这个功能，没法用。。。

**Comment by Yancey0623** [comment]
Hi @koolay , please follow #46, we have some discussion about the API design,  and I also look forward to your comment on it.
