### ISSUE TITLE
请问是否支持tunnel模式批量下载?

### ISSUE THREAD

**Issue by koolay** [sql-machine-learning/gomaxcompute#54]
例如使用tunnel_endpoint，走tunnel通道下载数据

**Comment by weiguoz** [comment]
Not supported yet.

**Comment by koolay** [comment]
我用Query，for next 最多只能查询出100条记录，是什么原因呢

**Comment by koolay** [comment]
这个query不合适返回大量数据？

**Comment by weiguoz** [comment]
是的, HTTP 接口只返回少量数据. 如果大量数据需要依赖 tunnel 的实现.

**Comment by koolay** [comment]
很纠结，找不到官方的协议说明，不能自己用go扩展sdk

**Comment by weiguoz** [comment]
> 很纠结，找不到官方的协议说明，不能自己用go扩展sdk

[Python SDK]( https://github.com/aliyun/aliyun-odps-python-sdk) 实现了基于 tunnel 的读写，我们可以参考实现。
