### ISSUE TITLE
不能捕获完整的错误信息

### ISSUE THREAD

**Issue by koolay** [sql-machine-learning/gomaxcompute#57]
在执行一个创建外部表的时候，返回的错误信息不全，信息如下:

`"ODPS-0130071:[1,1] Semantic analysis exception - external table checking failure, error message: null"`，不难看出，后面的`error message`应该是有内容的，不知道是否实现的xml协议有问题？

我查看了官方的一个[讨论](https://developer.aliyun.com/ask/116880)：

```
FAILED: ODPS-0130071:[1,1] Semantic analysis exception - external table checking failure,
 error message: {"RequestId":"0B0F8DE7-6BFE-4649-927E-EE8A5EFCB58D",
"HostId":"sts.aliyuncs.com",
"Code":"EntityNotExist.Role",
"Message":"The role not exists: acs:ram::1877037622533:role/aliyunodpsdefaultrole."
}
```

**Comment by weiguoz** [comment]
https://github.com/sql-machine-learning/gomaxcompute/blob/3aa1826ecaabc415ff12bd75cb1f993da571a108/client.go#L180
`parseResponseError`是对错误的理解，它被`parseResponse`调用。可以打印返回内容来找是否包含完整的错误信息

**Comment by koolay** [comment]
谢谢。

暂时没有找到原因，python的sdk也是相同的错误。
